### ISSUE TITLE
Block bootstrap

### ISSUE THREAD

**Issue by rofinn** [juliangehring/Bootstrap.jl#16]
I would like to implement `tsboot` from the R [boot](https://cran.r-project.org/web/packages/boot/index.html) package, do you have any recommendations on where to start (e.g., methods to overload or types to implement)? My understanding from the documentation is that `tsboot` is just performing a block-bootstrap, so I'm guessing I'd just need to implement a `BlockSampling` type?

**Comment by juliangehring** [comment]
All that should be needed for adding a new method should be a type that defines the sampling, e.g.
```julia
type BlockSampling <: BootstrapSampling
    nrun::Int
    # additional parameters go here, e.g. block size
end
``` 
and a `bootstrap` method that does the actual work, e.g.
```julia
function bootstrap(data, statistic::Function, sampling::BlockSampling)
    # insert your magic here
    # estimate `t0`: result of statistic applied to original data
    # bootstrap estimates `t1`: resample the data `nrun` and get a new estimate from the new data,
    # do this `nrun` times
    # return a type that inherits from a `BootstrapSample` type
end
```

The package also has some helper functions like `draw` and `pick` for vectors, but I'm not sure if you would need them in your case.

As a good starting point, you can have a look at the `BasicSampling` and `AntitheticSampling` methods in `src/bootsampling.jl`; the first is a rather simple, the latter a bit more complex example.

Just out of curiosity, how do you represent the input time series - is this simply a vector-like type or are there custom types for time series used by the julia community?

I hope this helps to get you started. As you have already seen, there isn't really any documentation about how to add new types so far - please let me know if you run into problems, details are unclear or if you have ideas for improvements.

**Comment by juliangehring** [comment]
Regarding the return type of the bootstrap method, we have the `NonParametricSampling` and `ParametricSampling` which both inherit from the abstract `BootstrapSample` type. The practical difference between the two is small and probably not relevant here: The `ParametricSampling` has an extra field for storing the model definition, and dispatch allows us two distinguish between the two for any downstream steps. For a simple block bootstrap, the `NonParametricSampling` should be all that is needed.

**Comment by rofinn** [comment]
Thanks that's very helpful. I was wondering if it would make sense to deprecate `draw!` in favour of extending `StatsBase.sample!` and `StatsBase.sample` with `sample!(::BoostrapSampling, x, o)` and `sample(::BootstrapSampling, x)`? I think for `BlockSampling` and `MESampling` (e.g., [maximum entropy bootstrap](https://www.jstatsoft.org/article/view/v029i05)) the primary difference is in how the samples are drawn rather than in the bootstrapping function itself. For the most part I'm just representing the time series as either a `Vector` or a `DataFrame`, to avoid overly specific dependencies.

**Comment by rofinn** [comment]
Closing as I think #17 mostly addressed this.

**Comment by juliangehring** [comment]
@rofinn Thank for you for implementing this.
