### ISSUE TITLE
Put function arguments first in signatures

### ISSUE THREAD

**Issue by ararslan** [juliangehring/Bootstrap.jl#22]
For example,
```julia
bootstrap(randn(20), mean, BasicSampling(100))
```
would become
```julia
bootstrap(mean, randn(20), BasicSampling(100))
```
This allows the use of `do` blocks to construct anonymous functions, e.g.
```julia
bootstrap(randn(20), BasicSampling(100)) do x
    sum(x) / length(x)
end
```

While that's likely not something that will occur that often when bootstrapping, it's conventional in Julia for functions to come first.

**Comment by juliangehring** [comment]
Thank you for the interesting suggestion. Is the "function-first" convention documented anywhere? I can't remember having heard about this before.

**Comment by ararslan** [comment]
It's listed in the style guide in the manual: https://docs.julialang.org/en/latest/manual/style-guide/#Write-functions-with-argument-ordering-similar-to-Julia's-Base-1. This was added fairly recently (within the 0.7 timeframe) after a discussion about the need to document the convention that was already in use but not actually documented.

**Comment by juliangehring** [comment]
Thanks for the pointer. In your experience, do you see any other advantages of the function-first order, apart from being able to supply the function via a `do` block?

**Comment by ararslan** [comment]
The primary advantage is consistency with Base, as mentioned in the style guide, and many (most?) code packages. This convention arose from the ability to use `do` blocks when the first argument is a function but that's its only technical significance.

**Comment by juliangehring** [comment]
I like the convention of having the function first, and the consistency with core package seems appealing. I'll need to have a closer look if I can bundle this with some other interface-breaking changes - to minimise the number of breaking changes for the user.

**Comment by ararslan** [comment]
It doesn't need to be breaking if you use deprecations, e.g.
```julia
@deprecate bootstrap(data, statistic::Function, sampling::BasicSampling) bootstrap(statistic, data, sampling)
```
That will let the old method continue to work just fine, it will simply emit a warning when the user calls that method.

**Comment by juliangehring** [comment]
No worries, I haven't forgotten this. I'll update the code after #24 is done.
