### ISSUE TITLE
Override functions from StatsBase

### ISSUE THREAD

**Issue by nalimilan** [juliangehring/Bootstrap.jl#23]
In the perspective of adding Bootstrap.jl to the list of default packages in Stats.jl (https://github.com/JuliaStats/Stats.jl/pull/4), it would be nice to use the `confint` and `stderror` functions from StatsBase instead of `ci` and `se`, and to add a method to `StatsBase.nobs` instead of defining a separate function.

**Comment by juliangehring** [comment]
Thanks for raining this, I wasn't aware of `Stats.jl`. I fully agree with your suggestions, the package can and should integrate better with `StatsBase`. I'll try to add these soon (possibly in combination with other interface related changes).

**Comment by juliangehring** [comment]
Since `nobs` is only used internally by the `Bootstrap` package, is having a general `nobs` in `StatsBase` very relevant? I'm not sure if there is a wide use for these methods; but if there is a broader interest, I'm happy to have it live in `StatsBase`.

**Comment by nalimilan** [comment]
Thanks. If `nobs` is internal then it's fine to keep it as is. It can always be exported later if needed.

**Comment by juliangehring** [comment]
Alright, all the renaming has been merged with #24.
