### ISSUE TITLE
is argument signature for draw! too restrictive?

### ISSUE THREAD

**Issue by kleinschmidt** [juliangehring/Bootstrap.jl#42]
The `draw!` method for abstract arrays requires that both arguments be the same type, but the destination array is created with `copy` which doesn't always give you back an AbstractArray of the same type: 

```julia
julia> typeof(view(1:100, 1:2:100))
SubArray{Int64,1,UnitRange{Int64},Tuple{StepRange{Int64,Int64}},true}

julia> typeof(copy(view(1:100, 1:2:100)))
Array{Int64,1}
```

**Comment by juliangehring** [comment]
Closed with #43.
