### ISSUE TITLE
Project.toml

### ISSUE THREAD

**Issue by colintbowers** [juliangehring/Bootstrap.jl#46]
Hi all,

Is it my imagination or is Bootstrap.jl missing a Project.toml and Manifest.toml? I'm currently working on wrapping routines from DependentBootstrap.jl using the Bootstrap.jl API and can easily add a Project.toml and Manifest.toml at the same time as part of the (eventual) pull request...

Cheers,

Colin

**Comment by juliangehring** [comment]
Well, it doesn't have one... I looked into adding one beginning of this year, but didn't see big advantages from my point of view. What would be the benefits of having the new toml files in your opinion?

**Comment by colintbowers** [comment]
It is not so much advantages, but more the fact that I'm pretty sure (although not certain) that you will *need* a Project.toml file at some point. Currently `Pkg` supports both REQUIRE files and Project.toml (which is essentially the replacement for REQUIRE), but I think the plan is to eventually get rid of REQUIRE files entirely.

To be honest, I'm surprised this hasn't caused a problem for `Bootstrap` already. Have you tried to change the dependencies of `Bootstrap` since Julia v1.0? I've checked out `Bootstrap` into a development branch, and although it compiled fine initially, as soon as I changed the dependencies (by adding a `using DependentBootstrap`) it refused to compile until I added a Project.toml file to the development branch. Certainly if you use `Pkg` to generate a new package today, it will auto-generate a Project.toml file and package uuid for you.

**Comment by juliangehring** [comment]
I have been using and developing the package without a manifest without problems, both with julia v1.0 and v1.1. Let me see if I can reproduce your findings.

**Comment by colintbowers** [comment]
Sounds good. In the meantime, I might post a clarifying question about this to Discourse for my own edification. If the intention really is for all packages to migrate from REQUIRE to Project.toml it would probably be a good idea to have this stated in a Discourse thread by a core dev.

**Comment by colintbowers** [comment]
Discourse question [here](https://discourse.julialang.org/t/the-future-of-require-and-project-toml-for-package-managers/22618). I'll be interested to see what the response is, since I've done some wider reading on this now, and some of the posts about the future of this stuff seem quite contradictory.

In the short term though, my reading agrees with your experience, i.e. I should have been able to alter the dependencies for Bootstrap with just a REQUIRE file without any problems. I'll look at it again this week. Please don't waste too much of your own time in the meantime :-)

**Comment by rofinn** [comment]
NOTE: Project.toml files work nicely with a Pkg3 environment based workflow. For example, running `julia --project=@.` in the root package directory will create a custom environment just for that package. This potentially avoids version incompatibilities with other dev'd packages and means that any packages added will automatically update the Project.toml.

**Comment by colintbowers** [comment]
OK, very clear answer from Stefan on the linked Discourse thread. REQUIRE is being retired soon, so `Bootstrap` will need a Project.toml. I've actually already done this as part of my work on https://github.com/juliangehring/Bootstrap.jl/issues/45, so if you're happy to wait a week or two, the file can just come through as part of my PR.

**Comment by juliangehring** [comment]
@colintbowers Alright, thanks for getting some clarification on that issue. If you already have `Project.toml` and `Manifest.toml`lying around, would you mind opening a separate PR for that? It can be super quick and dirty; but since missing those files is causing problems for working with the package for you (and potentially other), I'd like to get this in rather sooner than later. If you are busy with other things, I can also take a stab at this myself. Let me know what you prefer.

**Comment by colintbowers** [comment]
No probs, I'll get it done tonight, or at the latest tomorrow night (Australia time).

**Comment by juliangehring** [comment]
Closed with #48.
