### ISSUE TITLE
Broken compatibility against new release of StatsModels (v0.6.0)

### ISSUE THREAD

**Issue by mmolignano** [juliangehring/Bootstrap.jl#52]
Against the just released version of StatsModels (v0.6.0), this package is now giving me errors.

Not able to find "Formula".

**Comment by proudindiv** [comment]
Me too in StatsKit.

**Comment by juliangehring** [comment]
Thank for the report!
My time is unfortunately very limited over the next few weeks, but I'll try to look into it as soon as I can. Is working with any StatsModels versions <v0.6.0 an option for you as a temporary workaround?

**Comment by proudindiv** [comment]
Also with RCall:
=======================================================
using RCall;
R"require(forecast)";
=======================================================
┌ Info: Precompiling RCall [6f49c342-dc21-5d91-9882-a32aef131414]
└ @ Base loading.jl:1186
WARNING: could not import StatsModels.Formula into RCall
ERROR: LoadError: LoadError: UndefVarError: Formula not defined
=======================================================

**Comment by juliangehring** [comment]
Is RCall incompatible with Bootstrap or with StatsModels?

**Comment by proudindiv** [comment]
With StatsModels.  The Bootstrap failure seems to be a separate incompatibility loaded from StatsKit.

I ran into both of them in my program that I'm working on.

**Comment by mmolignano** [comment]
From my perspective, Bootstrap is incompatibile with the new version of StatsModels (0.6.0). I think it would be enough to add a compatibility requirement of StatsModels = "0.5.0" until you are able to update against their new version.

**Comment by mmolignano** [comment]
I see that there have been updates already committed and merged into the develop branch that add a Project.toml, as well as additional updates to remove the depracated REQUIRE file in #49. If these changes alone could be merged into master with an added compat statement that should allow us to use Bootstrap again until you get a chance to update against StatsModels v0.6.0.

**Comment by harryscholes** [comment]
Temporary fix:

```julia
pkg> add Bootstrap StatsModels@0.5
```

**Comment by juliangehring** [comment]
As @harryscholes mentioned, pinning the `StatsModels` to anything pre v0.6.0 will resolve this for now.

**Comment by juliangehring** [comment]
This should get fixed with the [v2.1.0 release](https://github.com/JuliaRegistries/General/pull/1596).

**Comment by juliangehring** [comment]
Closed with the release of v2.1.0.
I'll track the changes for making `Bootstrap` compatible with `StatsModels` v0.6 in #55.
