### ISSUE TITLE
Upgrade `Formulas` to `StatsModels` v0.6.0+

### ISSUE THREAD

**Issue by juliangehring** [juliangehring/Bootstrap.jl#55]
`StatsModels` v0.6.0 introduced a breaking redesign of its formulas which makes parts of `Bootstrap` incompatible with the latest versions of the package (see #52). Future versions of `Bootstrap` should adapt the new formula interface and become compatible with the lastest versions of `StatsModels`.

**Comment by kleinschmidt** [comment]
I'll have a look at this; somehow missed this one when I was checking
dependencies.

**Comment by kleinschmidt** [comment]
Okay I think there's a "quick and dirty" way to fix this and a deeper way to fix
it.  I'll make a PR with each and you can decide :)

**Comment by juliangehring** [comment]
If we merge #57, would #56 still be needed?

**Comment by kleinschmidt** [comment]
No, #57 supersedes #56.

**Comment by juliangehring** [comment]
Okay, thanks for the confirmation. Let's leave #56 open until #57 is merged, but I see no blockers for the latter.

**Comment by juliangehring** [comment]
Implemented in #57. Thanks, @kleinschmidt!
