### ISSUE TITLE
Interquartile range 

### ISSUE THREAD

**Issue by AhmedAlreweny** [juliangehring/Bootstrap.jl#69]
I suggest adding the [iqr](https://juliastats.org/StatsBase.jl/v0.23/scalarstats.html#StatsBase.iqr) to the estimators.

**Comment by juliangehring** [comment]
Could you share some more details about the idea? Where do you see the benefits?

**Comment by AhmedAlreweny** [comment]
It is an estimator that measure how the data are deviated from the median (similar to the std). The difference is that the std can be misleading if the distribution has outliers or heavy tail. In that case, the mean and std are replaced with the median and the iqr, respectively.

**Comment by juliangehring** [comment]
I was rather asking about where you think that the `iqr` is "missing" in the package and in which form it should be "added".

You can already use the `iqr` as an estimator:

```julia
bootstrap(StatsBase.iqr, data, BootstrapSampling)
```

Doesn't that work as expected?

**Comment by AhmedAlreweny** [comment]
Oh! I am sorry. I tried `bootstrap(StatsBase.iqr, data, BootstrapSampling)` and when it didn't work, I thought that it is not included. It is working fine. Thanks a lot!

**Comment by juliangehring** [comment]
Okay, happy to hear that it is working fine for you.
You can use an arbitrary estimator function with the package, as in this case coming from the `StatsBase` package. The `bootstrap` package doesn't distribute any particular statistics function and is designed to work with whatever estimator function that you choose.

**Comment by AhmedAlreweny** [comment]
> Okay, happy to hear that it is working fine for you.
> You can use an arbitrary estimator function with the package, as in this case coming from the `StatsBase` package. The `bootstrap` package doesn't distribute any particular statistics function and is designed to work with whatever estimator function that you choose, irrespectively of where the function is defined.

**Comment by AhmedAlreweny** [comment]
It is very clear now. Thanks a lot.
