### ISSUE TITLE
WARNING: using Bootstrap.data in module Main conflicts with an existing identifier

### ISSUE THREAD

**Issue by kescobo** [juliangehring/Bootstrap.jl#7]
Started seeing this warning popping up after upgrading to v1.0 on julia 0.5 release, and it's causing some errors to be thrown in my code. Any chance you could change the name or else extend the function in Base rather than overwriting it?

**Comment by juliangehring** [comment]
What module is causing the conflict? I can't reproduce the warning with a recent julia 0.5.0-dev+5179 version. Can you post a reproducible example?

**Comment by juliangehring** [comment]
I also can't get the warning with julia v0.5.0-rc2. I guess that is what you were referring to with "julia 0.5 release"?

**Comment by kescobo** [comment]
Hmm... I didn't check before, but this is only happening when using the Juno IDE in the Atom editor. In my file, I execute:

```
using DataFrames,
      Bootstrap
```

And don't get the warning. Then:

```
function getbootstrap(v, n=1000, i=0.95)
    bs = bootstrap(v, mean, BasicSampling(n))
    ci1 = ci(bs, BasicConfInt(i))
    return ci1[1]
end
```

And this spits the warning:
```
WARNING: Method definition getbootstrap(Any) in module Main at /Users/KBLaptop/computation/Science/gender-comp-bio/src/bootstrapping.jl:6 overwritten at /Users/KBLaptop/computation/Science/gender-comp-bio/src/bootstrapping.jl:6.
WARNING: Method definition getbootstrap(Any, Any) in module Main at /Users/KBLaptop/computation/Science/gender-comp-bio/src/bootstrapping.jl:6 overwritten at /Users/KBLaptop/computation/Science/gender-comp-bio/src/bootstrapping.jl:6.
WARNING: Method definition getbootstrap(Any, Any, Any) in module Main at /Users/KBLaptop/computation/Science/gender-comp-bio/src/bootstrapping.jl:6 overwritten at /Users/KBLaptop/computation/Science/gender-comp-bio/src/bootstrapping.jl:6.
```

But I just opened the REPL and did the same thing, but did not get a warning. So this might be a problem with Juno - I'll open an issue over there.

**Comment by kescobo** [comment]
Julia `Version 0.5.0-rc2+0`, what you get when you do `git checkout release-0.5`

**Comment by juliangehring** [comment]
Ok, thank you for the example. When does the `WARNING: using Bootstrap.data in module Main conflicts with an existing identifier` occur? The warning in your example seems to be a different one.

**Comment by kescobo** [comment]
Ahh, excellent point. I cannot now reproduce that original warning and the associated errors :-/

It was happening when I was including a script that had the above function definition, and then using it on some `DataFrame` columns, but I just went back and repeated the procedure. I'll let you know if it pops up again, but I can't seem to find it...

**Comment by juliangehring** [comment]
No worries - let me know in case it shows up again.

**Comment by kescobo** [comment]
Will do!
