### ISSUE TITLE
outdated compat info at General Registry

### ISSUE THREAD

**Issue by FuZhiyu** [juliangehring/Bootstrap.jl#73]
Hi,

The entry of this package on [general registry](https://github.com/JuliaRegistries/General/blob/89ae08aab842ed801073c173601c15bf7ad436b9/B/Bootstrap/Compat.toml#L23) is outdated. It doesn't allow for the latest DataFrames.jl@0.22.

I'm not familiar with the registry mechanism, but it seems the issue is caused by the compat rule in this form

PackageD = ">=0.4"
which does not meet the criteria for automatic merging. Could you update the registry info? Many thanks for this handy package!

**Comment by nalimilan** [comment]
See #74.

**Comment by juliangehring** [comment]
Should be fixed by #74 and the release of v2.2.1.
