### ISSUE TITLE
[question] how do you control or limit the sample size? 

### ISSUE THREAD

**Issue by Boxylmer** [juliangehring/Bootstrap.jl#85]
Correct me if Im mistaken in my understanding of bootstrapping, I'm going to basically use this as a more robust version of jackknifing. 

I have data that's used to fit a model and I want to apply bootstrapping to determine to confidence of 2 or 3 fitted parameters. The data usually ranges from 5-13 data points and the model will not fit less than 3 or so. 

1. Is there a way to ensure all resampling sets contain at least a certain number of data points? 
2. How do we check or specify this?
3. What if I'd like to resample some data set of size M to many sets of size N where N<M?

**Comment by juliangehring** [comment]
All algorithms implemented in the package preserve the size of the input data set. This means that if your input data set consists of N data points, all resampled data sets will contain exactly N data points.
There are bootstrapping algorithms for N out of M resampling but these are not covered by the package.

**Comment by Boxylmer** [comment]
I see! Thank you for the explanation!

How does this work for models that aren't order dependent? Say we're sampling from some set of data points:
[(1, 0.2), (2, 4.5), (3, 6.5), (5, 19)]

and we resample with replacement to 

[(5, 19), (1, 0.2), (5, 19), (2, 4.5)]

Is this not the same as effectively removing the (3, 6.5) data point in your sample, and therefore boiling down to jackknifing?

**Comment by juliangehring** [comment]
>How does this work for models that aren't order dependent? Say we're sampling from some set of data points:
[(1, 0.2), (2, 4.5), (3, 6.5), (5, 19)]
and we resample with replacement to
[(5, 19), (1, 0.2), (5, 19), (2, 4.5)]
Is this not the same as effectively removing the (3, 6.5) data point in your sample, and therefore boiling down to jackknifing?

No. Jack-knifing gives you

[(1, 0.2), (2, 4.5), (5, 19)]

while bootstrapping gives you e.g.

[(5, 19), (1, 0.2), (5, 19), (2, 4.5)]

(5, 19) are considered to be 2 independent observations here. The moments and even the number of observations of both samples are different.

> Further, in the previous case, wouldn't many sample sets be equivalent? e.g., [(5, 19), (1, 0.2), (5, 19), (2, 4.5)] = [(5, 19), (5, 19), (1, 0.2), (2, 4.5)]

They are equivalent in the sense that a statistic that doesn't care about the order of the observations gives you the same result for both samples.
They are different samples for the bootstrap and fundamental to what makes the bootstrap work.
