### ISSUE TITLE
Bump Distributions.jl to 0.25

### ISSUE THREAD

**Issue by bkamins** [juliangehring/Bootstrap.jl#88]
Would Bootstrap.jl work with Distributions.jl 0.25?

**Comment by bkamins** [comment]
Also I have just noticed that in `draw!` you could write:
```
function draw!(x::AbstractMatrix, o::AbstractMatrix)
    idx = sample(1:nobs(x), nobs(o))
    o .= view(x, idx, :)
    return o
end
```
as it should be faster (not tested).

For data frames the same pattern would work, but what you have now should be efficient so it can be left as is (the `!` row selector is non-copying so the code is efficient).

**Comment by juliangehring** [comment]
Thanks for raising this. Bootstrap v2.3.3 has added support for Distributions v0.25.

I have also added CompatHelper to the repo (#89) and future dependency updates will now trigger pull requests automatically.

**Comment by juliangehring** [comment]
I'll take a look at the changes for the `draw!` method. I considered the changes you suggested a while ago but couldn't find any performance improvements. Maybe things have changes since then and now it indeed be faster - let's see if we can get some good benchmark numbers before making decision on this.

**Comment by bkamins** [comment]
```
julia> function draw!(x::AbstractMatrix, o::AbstractMatrix)
           idx = sample(1:nobs(x), nobs(o))
           for (to, from) in enumerate(idx)
               o[to,:] = x[from,:]
                   end
           return o
       end
draw! (generic function with 1 method)

julia> function draw2!(x::AbstractMatrix, o::AbstractMatrix)
           idx = sample(1:nobs(x), nobs(o))
           o .= view(x, idx, :)
           return o
       end
draw2! (generic function with 1 method)

julia> x = rand(1000, 1000);

julia> o = similar(x);

julia> @btime draw!($x, $o);
  13.830 ms (1001 allocations: 7.76 MiB)

julia> @btime draw2!($x, $o);
  2.377 ms (1 allocation: 7.94 KiB)
```

**Comment by bkamins** [comment]
For mor repetitions it is even bigger:
```
julia> @btime draw!($x, $o);
  171.982 ms (10002 allocations: 77.59 MiB)

julia> @btime draw2!($x, $o);
  19.251 ms (2 allocations: 78.20 KiB)
```

**Comment by bkamins** [comment]
In general, if we found something faster than:
```
o .= view(x, idx, :)
```
then we should open an issue in Julia Base I think as then the above code should be fixed.

**Comment by juliangehring** [comment]
Nice, thanks for sharing!

**Comment by bkamins** [comment]
BTW: you might want to have a look at the last part of the tutorial in https://github.com/bkamins/JuliaCon2021-DataFrames-Tutorial. If you would have any comments on how I use Bootstrap.jl please let me know. Thank you!
